- name: Set up snapshot alias
  set_fact:
    snapshot: "{{ item.value }}"
    snapshot_name: "{{ item.key }}"

- name: Set command to init command
  set_fact:
    duplicacy_command: "{{ duplicacy }} init {{ snapshot.init_args }}"

- name: Create scripts directory
  file:
    name: "{{ DUPLICACY.scripts }}"
    state: directory

- name: Create repository init script
  template:
    src: duplicacy_snapshot.j2
    dest: "{{ DUPLICACY.scripts }}/{{ snapshot_name }}.init.sh"
    mode: 0770

- name: Initialize the storage
  command: "{{ DUPLICACY.scripts }}/{{ snapshot_name }}.init.sh"
  register: output
  # 100 means that the storage is already initialized
  failed_when: "output.rc != 0 and output.rc != 100"
  changed_when: "output.rc != 100"

- name: Install filters
  template:
    src: duplicacy_filters.j2
    dest: "{{ snapshot.root }}/.duplicacy/filters"
    mode: 0660

- name: Set command to backup command
  set_fact:
    duplicacy_command: "nice -n 19 ionice -c 3 {{ duplicacy }} backup {{ snapshot.update_args }}"

- name: Create backup script
  template:
    src: duplicacy_snapshot.j2
    dest: "{{ DUPLICACY.scripts }}/{{ snapshot_name }}.backup.sh"
    mode: 0770

- name: Schedule backup in cron
  cron:
    name: "duplicacy-{{ snapshot_name }}"
    minute: "{{ snapshot.cron.minute }}"
    hour: "{{ snapshot.cron.hour }}"
    job: "{{ DUPLICACY.scripts }}/{{ snapshot }}.backup.sh > /dev/null"
    cron_file: "duplicacy-{{ snapshot_name }}"
    state: present
