- name: Set up site alias
  set_fact:
    site: "{{ item.value }}"
    site_name: "{{ item.key }}"

- name: Set command to init command
  set_fact:
    duplicacy_command: "{{ duplicacy }} init {{ site.init_args }}"

- name: Create scripts directory
  file:
    name: "{{ DUPLICACY.scripts }}"
    state: directory

- name: Create repository init script
  template:
    src: duplicacy_site.j2
    dest: "{{ DUPLICACY.scripts }}/{{ site_name }}.init.sh"
    mode: 0770

- name: Initialize the repository
  command: "{{ DUPLICACY.scripts }}/{{ site_name }}.init.sh"
  register: output
  # 100 means that the repo is already initialized
  failed_when: "output.rc != 0 and output.rc != 100"
  changed_when: "output.rc != 100"


- name: Install filters
  template:
    src: duplicacy_filters.j2
    dest: "{{ site.directory }}/.duplicacy/filters"
    mode: 0660

- name: Set command to backup command
  set_fact:
    duplicacy_command: "nice -n 19 ionice -c 3 {{ duplicacy }} backup {{ site.update_args }}"

- name: Create backup script
  template:
    src: duplicacy_site.j2
    dest: "{{ DUPLICACY.scripts }}/{{ site_name }}.backup.sh"
    mode: 0770

- name: Schedule backup in cron
  cron:
    name: "duplicacy-{{ site_name }}"
    minute: "{{ site.cron.minute }}"
    hour: "{{ site.cron.hour }}"
    job: "{{ DUPLICACY.scripts }}/{{ site_name }}.backup.sh > /dev/null"
    cron_file: "duplicacy-{{ site_name }}"
    state: present
