---
- name: Download download duplicacy
  get_url:
    url: "{{ DUPLICACY_INSTALL.url }}"
    dest: "{{ DUPLICACY_TARGET_DIRECTORY }}"
    checksum: sha256:{{ DUPLICACY_INSTALL.sha256sum }}
    mode: "555"

- name: Install site scripts
  include: create-site.yaml
  with_dict: "{{ DUPLICACY_SITES }}"

